name: bpoe-mongo-playground,
services:
  mongodb:
    image: mongo:8.0.6
    container_name: mongos02
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ../temp/mongo_pg:/data/db
    ports:
      - "27017:27017"
